"""Four files state the world's size independently. They must agree.

WHY THIS EXISTS
The terrain guard added on 2026-07-31 -- the bound that stops a robot being
commanded off the 500 m heightfield and taking Gazebo down with it -- is a box
test, and a box test is only as good as the box. The trouble is that the box is
declared in four places, in four formats, for four different consumers:

  1. models/lunar_terrain/heightmaps/terrain_datum.json  ``world_size_m``
     GENERATED by scripts/generate_heightmap.py. The authority: it is the
     number the PNGs were actually built at.
  2. models/lunar_terrain/model.sdf                      ``<size>500 500 z</size>``
     What Gazebo loads. Already pinned to (1) for its Z by
     test_heightmap_datum.py, which did not look at the two XY numbers.
  3. config/world_params.yaml                            ``world.bounds``
     Read by battery_node for the PSR test and by TerrainBounds.
  4. selene_agent/config/nav_params.yaml     ``grid_width * grid_resolution``
     etc. The A* grid, whose extent is what AStarPlanner refuses goals outside.

and the safety margin is declared twice more, in (3) and (4), plus once in
selene_orchestrator/config/orchestrator_params.yaml for the operator-facing
refusal.

None of those files can see any of the others. A guard whose numbers have
drifted is worse than no guard: it reads as protection and refuses the wrong
set. This project has already been bitten by exactly that shape of defect twice
-- a heightmap datum that no config could see (test_heightmap_datum.py's own
docstring) and a parameter that was declared and never read (register D-09) --
so the numbers are pinned to each other here rather than to a comment.

NO ROS, NO GAZEBO, NO PILLOW. Pure file reads; runs on every push.
"""

import json
import os
import re

import pytest
import yaml

_HERE = os.path.dirname(os.path.abspath(__file__))
_PKG = os.path.dirname(_HERE)
_REPO = os.path.dirname(_PKG)

DATUM_JSON = os.path.join(
    _PKG, 'models', 'lunar_terrain', 'heightmaps', 'terrain_datum.json')
MODEL_SDF = os.path.join(_PKG, 'models', 'lunar_terrain', 'model.sdf')
WORLD_YAML = os.path.join(_PKG, 'config', 'world_params.yaml')
NAV_YAML = os.path.join(
    _REPO, 'selene_agent', 'config', 'nav_params.yaml')
ORCH_YAML = os.path.join(
    _REPO, 'selene_orchestrator', 'config', 'orchestrator_params.yaml')


@pytest.fixture(scope='module')
def datum():
    with open(DATUM_JSON) as handle:
        return json.load(handle)


@pytest.fixture(scope='module')
def world():
    with open(WORLD_YAML) as handle:
        return (yaml.safe_load(handle) or {})['world']


@pytest.fixture(scope='module')
def nav():
    with open(NAV_YAML) as handle:
        return (yaml.safe_load(handle) or {})['navigation']


@pytest.fixture(scope='module')
def orchestrator_params():
    with open(ORCH_YAML) as handle:
        loaded = yaml.safe_load(handle) or {}
    return loaded['orchestrator_node']['ros__parameters']


@pytest.fixture(scope='module')
def sdf_xy():
    """The two XY numbers on each ``<size>`` element of model.sdf.

    test_heightmap_datum.py parses the same elements for their Z and asserts the
    two Z values must DIFFER; the XY pair must be identical between them and
    equal to world_size_m, which nothing checked.
    """
    text = open(MODEL_SDF).read()
    # COMMENTS STRIPPED FIRST. model.sdf's own explanation of gz-sim's
    # normalisation rule quotes a synthetic `<size>100 100 30</size>` from the
    # measurement that established it, and a naive findall picks that up as a
    # third heightmap. test_heightmap_datum.py sidesteps the same trap by
    # hardcoding `500` into its pattern, which is precisely the number this file
    # exists to stop hardcoding.
    text = re.sub(r'<!--.*?-->', '', text, flags=re.S)
    sizes = re.findall(
        r'<size>\s*([\d.]+)\s+([\d.]+)\s+[\d.]+\s*</size>', text)
    assert len(sizes) == 2, f'expected 2 <size> elements, found {len(sizes)}'
    return [(float(w), float(h)) for w, h in sizes]


# --------------------------------------------------------------- the extent

def test_the_sdf_footprint_is_the_generated_world_size(datum, sdf_xy):
    size = float(datum['world_size_m'])
    for width, height in sdf_xy:
        assert (width, height) == pytest.approx((size, size), abs=1e-9), (
            f'model.sdf declares a {width} x {height} m heightmap while '
            f'generate_heightmap.py built the images at {size} m. Every world '
            f'coordinate is then scaled by {size / width:.6f}.')


def test_the_collision_and_visual_heightmaps_share_a_footprint(sdf_xy):
    """Their Z values must differ (see test_heightmap_datum); XY must not."""
    assert sdf_xy[0] == sdf_xy[1], (
        f'collision {sdf_xy[0]} and visual {sdf_xy[1]} cover different ground; '
        f'the robot would drive on a surface that is not where it is drawn')


def test_world_params_bounds_are_the_terrain_footprint(datum, world):
    size = float(datum['world_size_m'])
    bounds = world['bounds']
    assert float(bounds['x_max']) - float(bounds['x_min']) == \
        pytest.approx(size, abs=1e-9)
    assert float(bounds['y_max']) - float(bounds['y_min']) == \
        pytest.approx(size, abs=1e-9)
    # Centred on the origin, which is what <pos>0 0 0</pos> on the heightmap
    # means and what TerrainGuard's single half_extent assumes.
    assert float(bounds['x_min']) == pytest.approx(-size / 2.0, abs=1e-9)
    assert float(bounds['y_min']) == pytest.approx(-size / 2.0, abs=1e-9)


def test_the_nav_grid_covers_exactly_the_terrain(datum, nav, world):
    """The A* grid extent IS the terrain extent, and that is load-bearing.

    ``AStarPlanner`` refuses a goal outside the grid, and the terrain margin is
    applied relative to the grid edge. If the grid were larger than the terrain,
    the margin would be measured from empty space and the guard would pass goals
    that are off the map; if smaller, robots could not reach real ground.
    """
    size = float(datum['world_size_m'])
    resolution = float(nav['grid_resolution'])
    span_x = float(nav['grid_width']) * resolution
    span_y = float(nav['grid_height']) * resolution
    assert (span_x, span_y) == pytest.approx((size, size), abs=1e-9)
    assert float(nav['origin_x']) == pytest.approx(
        float(world['bounds']['x_min']), abs=1e-9)
    assert float(nav['origin_y']) == pytest.approx(
        float(world['bounds']['y_min']), abs=1e-9)


def test_the_orchestrator_half_extent_is_the_terrain_half_extent(
        datum, orchestrator_params):
    size = float(datum['world_size_m'])
    assert float(orchestrator_params['terrain_half_extent_m']) == \
        pytest.approx(size / 2.0, abs=1e-9), (
            'orchestrator_params.yaml would refuse operator targets against a '
            'different box from the one the agent and the terrain use')


# --------------------------------------------------------------- the margin

def test_the_three_margins_are_one_number(world, nav, orchestrator_params):
    """world_params, nav_params and orchestrator_params must all say the same.

    They are three files because three different processes need the number and
    none of them reads the others' configuration. That is a legitimate
    duplication of a VALUE; it is not a licence for three different values.
    A larger orchestrator margin would refuse targets the agent would happily
    drive to; a smaller one would pass targets the agent then refuses, which
    presents as a task that is accepted and then fails for no visible reason.
    """
    margins = {
        'world_params.yaml world.safety_margin_m':
            float(world['safety_margin_m']),
        'nav_params.yaml navigation.terrain_margin_m':
            float(nav['terrain_margin_m']),
        'orchestrator_params.yaml terrain_margin_m':
            float(orchestrator_params['terrain_margin_m']),
    }
    assert len(set(margins.values())) == 1, (
        'the terrain safety margin disagrees across configuration files:\n'
        + '\n'.join(f'  {k} = {v}' for k, v in margins.items()))


def test_the_margin_clears_the_last_collision_sample(datum, world):
    """The margin must at least reach the heightfield's outermost SAMPLE.

    gz-sim builds the collision surface from a finite lattice: 129 samples over
    500 m puts the last one 1.953 m inside the nominal edge, and the operator's
    ODE abort log reports the broadphase heightfield AABB as +/-248.062, which
    is that inset within the coarse map's quantisation. Beyond it there is no
    ground even though the ``<size>`` says there is.
    """
    size = float(datum['world_size_m'])
    grid = int(datum['collision']['grid'])
    half_cell = (size / (grid - 1)) / 2.0
    margin = float(world['safety_margin_m'])
    assert margin > half_cell, (
        f'safety_margin_m {margin} does not clear the {half_cell:.3f} m inset '
        f'of the last collision sample on a {grid}x{grid} heightmap')
    # And it must leave a usable world behind.
    assert margin < size / 10.0, (
        f'safety_margin_m {margin} removes more than 10% of a {size} m world')
